[package]
name = "ickle"
version = "0.2.0"
authors = ["Kaz Wesley <kaz@lambdaverse.org>"]
edition = "2018"
description = "A little iCal parser."
license = "MIT OR Apache-2.0"
keywords = ["ical"]
repository = "https://github.com/kazcw/ickle"

[dependencies]
